/**:
  ros__parameters:
    point_filters: |
      {
        "ring_section_filter": [
        [0, 0, 93],[0, 266, 360],
        [1, 0, 93],[1, 266, 360],
        [2, 0, 93],[2, 266, 360],
        [3, 0, 93],[3, 266, 360],
        [4, 268, 360],
        [5, 268, 360],
        [6, 268, 360],
        [7, 268, 360],
        [8, 268, 360],
        [10, 272, 360],
        [11, 272, 360],
        [12, 272, 360],
        [13, 272, 360],
        [14, 266, 360],
        [15, 266, 360],
        [16, 266, 360],
        [17, 0, 96],[17, 266, 360],
        [18, 0, 96],[18, 263, 360],
        [19, 0, 96],[19, 263, 360],
        [20, 0, 96],[20, 263, 360],
        [21, 0, 96],[21, 263, 360],
        [22, 270, 360],
        [23, 270, 360],
        [24, 270, 360],
        [29, 0, 96],
        [30, 0, 96],[30, 267, 360],
        [31, 0, 96],[31, 267, 360],
        [32, 0, 96],[32, 267, 360],
        [33, 0, 96],
        [38, 272, 360],
        [45, 0, 93],[45, 267, 360],
        [50, 0, 98],
        [51, 0, 98],
        [52, 0, 98],
        [53, 0, 98],
        [54, 0, 98],
        [57, 0, 93],
        [58, 0, 93],[58, 261, 360],
        [59, 0, 93],[59, 261, 360],
        [60, 0, 93],[60, 261, 360],
        [61, 0, 93],
        [72, 269, 360],
        [73, 0, 88],[73, 269, 360],
        [74, 0, 88],[74, 269, 360],
        [75, 0, 90],
        [76, 0, 94],
        [77, 0, 94],
        [78, 0, 94],
        [79, 0, 94],
        [80, 0, 94],
        [81, 0, 90],
        [82, 0, 90],
        [83, 0, 90],
        [84, 0, 88],
        [85, 0, 88],
        [86, 0, 88],
        [88, 273, 360],
        [89, 273, 360],
        [90, 273, 360],
        [91, 0, 93],[91, 273, 360],
        [92, 0, 93],[92, 268, 360],
        [93, 0, 93],[93, 273, 360],
        [94, 0, 93],[94, 273, 360],
        [95, 0, 93],[95, 273, 360],
        [96, 0, 93],[96, 273, 360],
        [97, 0, 93],[97, 273, 360],
        [98, 0, 93],[98, 273, 360],
        [99, 0, 93],[99, 273, 360],
        [100, 0, 93.5],[100, 273, 360],
        [101, 273, 360],
        [102, 273, 360],
        [103, 274, 360],
        [104, 274, 360],
        [105, 275, 360],
        [106, 0, 95],[106, 275, 360],
        [107, 0, 95],[107, 275, 360],
        [108, 0, 95],[108, 275, 360],
        [109, 0, 95],
        [110, 0, 95],
        [111, 0, 90],
        [112, 0, 93],
        [113, 0, 93],
        [114, 0, 93],
        [115, 0, 93],
        [116, 0, 93],
        [117, 0, 93],
        [118, 0, 96],[118, 265, 360],
        [119, 0, 96],[119, 265, 360],
        [120, 0, 98],[120, 265, 360],
        [121, 0, 98],[121, 265, 360],
        [122, 0, 98],[122, 258, 360],
        [123, 0, 98],[123, 258, 360],
        [124, 0, 98],[124, 258, 360],
        [125, 0, 100],[125, 256, 360],
        [126, 0, 100],[126, 256, 360],
        [127, 0, 100],[127, 256, 360]
        ]
      }
